# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test
  - sonarqube-check
  - docker-deploy
#  - sonarqube-vulnerability-report

build:
  stage: build
  script:
    - ./gradlew clean assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 hour

test:
  stage: test
  script:
    - ./gradlew test

sonarqube-check:
  stage: sonarqube-check
  script: ./gradlew test sonar jacocoTestReport

docker-deploy:
  stage: docker-deploy
  script:
    - echo "Stopping and removing existing Docker container..."
    - docker stop revend-be-container -or $true
    - docker rm revend-be-container -or $true
    - echo "Building Docker image..."
    - docker build -t revend-backend:latest .
    - echo "Running Docker container..."
    - docker run --name revend-be-container -p 8080:8080 --network revend-network -d revend-backend:latest
  only:
    - main